package com.jek.recipetaste;
import java.util.ArrayList;

public class ResepData {
    private static String[][] RecipeDetail = new String[][] {
            {"Rendang", "Durasi memasak : 80 menit","https://tasteasianfood.com/wp-content/uploads/2015/10/beef-rendang-3a.jpg " ,
                    "Bahan Rendang : \n- Daging sapi 1kg(bagian has luar potong setebal jari) \n- Santan dari kelapa hijau 3 liter \n- Daun kunyit 2 lembar \n- Daun jeruk 3 lembar \n- Lengkuas 5cm \n- Serai 2 batang \n- Daun salam 5 lembar \n- Asam kandis 5 buah \n \nBumbu Rendang (haluskan) : \n- Cabe merah tanpa biji 150gr \n- Jahe 100gr \n- Lengkuas 6cm \n- Bawang merah 100gr \n- Kunyit 3cm \n- Bawang putih 5 butir \n- Merica 10 butir \n- Kemiri 5 butir \n- Garam secukupnya\n \nCara Membuat : \n1. Rebus santan dengan bumbu halus, daun jeruk, dan asam kandis. Aduk terus agar santan tidak pecah sampai mengental. \n2. Jika sudah mulai keluar minyak, masukkan potongan daging sapi. \n3. Aduk terus sampai matang dengan api sedang. Angakat dan sajikan."},

            {  "Soto Padang",  "Durasi memasak : 30 menit","https://4.bp.blogspot.com/-tASNUR3PaH8/WPd-emr16FI/AAAAAAAAAWc/5bhTNL198HwY4ziojhvz0Yc0RsRpLzYGACPcB/s1600/SOTO%2BPADANG%2Batau%2BSOTO%2BPADANG%2B%2528%2BP3%2B%2529.jpg ",
                    "Bahan Soto : \n- Daging ayam 750gr (lumuri air jeruk nipis, diamkan 15 menit) \n- Air 2 liter \n- Daun salam 3 lembar \n- Daun jeruk 4 lembar \n- Serai 1 batang \n- Kapulaga 3 butir \n- Kembang lawang 2 buah \n- Cengkeh 3 butir \n- Daun bawang 2 batang \n- Saus tiram 1sdt\n \nBumbu Soto : \n- Bawang putih 3 siung \n- Bawang merah 6 butir \n- Jahe 2cm \n- Kunyit 2cm \n- Lengkuas 2cm \n- Kemiri 3 butir\n \nBahan Sambal : \n- Cabe rawit merah 17 buah \n- Kuah soto 4 sendok sayur\n \nBahan Pelengkap : \n- Mie soun (seduh dengan air panas) \n- Bawang goreng \n- Daun seledri \n- Jeruk nipis \n- Telur rebus \n- Perkedel kentang \n- Kerupuk merah \n- Kecap\n \nCara membuat : \n1. Rebus ayam dalam air. Sementara itu tumis bumbu soto padang sampai harum, tambahkan daun jeruk, serai dan daun salam. Aduk rata. \n2. Tambahkan kapulaga, kembang lawang, cengkeh dan kayu manis, aduk sebentar. \n3. Masukkan tumisan bumbu ke dalam rebusan ayam, masak hingga mendidih. Masukkan daun bawang dan saus tiram. Masak kembali dengan api kecil hingga daun bawang layu. \n4. Angkat potongan daging ayam, tiriskan. Goreng ayam sampai kecoklatan, angkat dan tiriskan.\n \nPenyajian Soto : \n1. Ambil mangkuk, tata soun, suwiran ayam, bawang goreng dan seledri, jangan lupa telurnya. Tuangkan kuah soto diatasnya. Soto padang siap dinikmati. \n2. Untuk membuat sambal, cukup rebus cabe rawit dengan kuah soto kemudian blender."},

            {  "Ikan Cuka Gurame", "Durasi memasak : 45 menit","https://i.ytimg.com/vi/s_YEp-6BPb4/hqdefault.jpg" ,
                    "Bahan Ikan Cuka Gurame : \n- Ikan gurame 1 ekor \n- Cuka 1sdm \n- Air jeruk nipis 1sdm + garam 1sdt \n- Garam 1sdt \n- Gula pasir 1sdt \n- Air 750ml \n- Minyak goreng secukupnya\n \nCara membuat : \n1. Lumuri ikan gurame dengan garam dan air jeruk nipis, diamkan sekitar 30 menit. Cuci bersih dan tiriskan. \n2. Selanjutnya goreng ikan gurame sampai matang namun jangan sampai kering. \n3. Ambil 4sdm minyak bekas menggoreng gurame, tumis bumbu yang telah dihaluskan sampai harum. \n4. Masukkan air, maska sampai mendidih. Tambahkan garam, gula dan cuka. Masukkan ikan gurame goreng, masak sebentar, angkat dan sajikan."},

            { "Kalio Ayam", "Durasi memasak : 60 menit","https://www.resepkoki.id/wp-content/uploads/2017/04/Resep-Kalio-Ayam-1024x1017.jpg " ,
                    "Bahan Ayam : \n- Ayam kampung 2 ekor, potong 4 bagian \n- Air jeruk nipis 1sdm + garam 1sdt \n- Daun kunyit 1 lembar \n- Daun jeruk 3 lembar \n- Serai 1 batang (memarkan) \n- Cabe merah giling 2sdm \n- Santan kental 500ml \n- Santan encer 1 liter \n- Minyak goreng secukupnya\n \nBumbu Kalio : \n- Bawang merah 10 butir \n- Bawang putih 4 siung \n- Ketumbar 2sdm \n- Kemiri 5 butir \n- Jahe 1 ruas \nKunyit 1 ruas (bakar) \n- Lengkuas 2 ruas \n- Garam secukupnya\n \nCara Membuat : \n1. Lumuri ayam dengan air jeruk nipis lalu diamkan sekitar 15 menit. \n2. Panaskan minyak goreng, tumis bumbu halus, daun jeruk, daun kunyit dan serai sampai beraroma harum. \n3. Masukkan cabe merah giling, aduk sampai mendidih. \n4. Masukkan daging ayam, masak sampai daging berubah warna dan kuah mendidih. Tambahkan santan encer, masak sampai daging lunak. \n5. Tuangkan santan kental sambil diaduk-aduk pelan diatas api kecil sampai santan berminyak. \n6. Siapkan piring saji, tata ayam kalio diatas piring. Ayam kalio siap dihidangkan. "},

            {  "Gulai Kepala Ikan Kakap", "Durasi memasak : 45 menit","https://d15hng3vemx011.cloudfront.net/attachment/24919022553008566215.large" ,
                    "Bahan Gulai Kepala Ikan Kakap : \n- Kepala ikan kakap 900gr (potong 2 bagian) \n- Serai 1 batang \n- Daun salam 10 lembar \n- Daun padan 1 lembar, sobek-sobek dan ikat \n- Santan 750cc dari 1 butir kelapa \n- Kelapa parut 2sdm (sangrai tumbuk halus) \n- Belimbing sayur 5 buah \n- Air jeruk nipis 1sdm \n- Garam 2sdt \n- Minyak 3sdm\n \nBumbu Gulai : \n- Cabe merah 17 buah \n- Kunyit 1cm (cincang) \n- Jahe 1cm (cincang) \n- Bawang putih 3 butir \n- Bawang merah 7 butir \n- Ketumbar 1sdm (sangrai) \n- Merica bubuk 1/2sdt \n- Asam 1sdm \n- Garam secukupnya\n \nCara membuat : \n1. Lumuri kepala kakap dengan jeruk nipis dan garam samai rata. Diamkan 40 menit, tiriskan. \n2. Lumuri kembali dengan kelapa tumbuk. Sisihkan. \n3. Haluskan bumbu halus, tumis dengan minyak bersama serai, dan daun pandan sampai harum. \n4. Tuangkan santan, aduk-aduk sampai mendidih, masukkan daun salam, kepala ikan kakap, dan belimbing sayur, aduk rata. \n5. Masak dengan api sedang hingga matang merata dan kuah agak berminyak sambil diaduk agar santan tidak pecah. Angkat dan sajikan. "},

            {  "Dendeng Bakar", "Durasi memasak : 60 menit","https://selerasa.com/wp-content/uploads/2015/06/images_daging_dendeng-batokok-bakar.jpg " ,
                    "Bahan Dendeng Bakar : \n- Daging sapi 500gr \n- Air asam jawa \n- Minyak olesan\n \nBumbu Halus : \n- Bawang putih 4 siung \n- Gula merah 2sdm \n- Bawang merah 12 butir \n- Ketumbar 2sdm \n- Jahe 2 ruas \n- Lengkuas 1 ruas \n- Kunyit 2 ruas (sangrai) \n- Garam 1sdt\n \nBahan Sambal : \n- Bawang putih 2 siung \n- Bawang merah 6 siung \n- Cabe rawit merah 15 buah \n- Gula pasir 1/2sdt \n- Jeruk nipis 1sdt \n- Minyak goreng 3sdm \n- Garam 1sdt\n \nCara Membuat : \n1. Iris daging, remas-remas dengan bumbu yang telah dihaluskan, siram dengan air asam jawa. Diamkan 1 jam sampai bumbu meresap sambil sesekali dibalik. \n2. Memarkan daging yang telah dibumbui, pukul-pukul. Panggang dendeng daging diatas api, bolak balik sambil diolesi minyak sampai matang. ANgkat dan sajikan dengan sambal.\n \nMembuat sambal : \n1. Iris tipis 3 buah bawang merah dan 3 buah bawang putih. \n2. Haluskan cabe dengan sisa bawang. Tumis bawang merah dan putih hingga harum lalu masukkan cabe yang sudah dihaluskan. \n3. Tambahkan gula pasir, garam dan jeruk nipis. Tumis sampai matang sambil diaduk-aduk. "},

            { "Dendeng Balado", "Durasi memasak : 45 menit","http://www.dapurkobe.co.id/wp-content/uploads/balado-daging-kering.jpg ",
                    " Bahan Dendeng Balado : \n- Daging sapi 600gr \n- garam 2sdm \n- Minyak goreng 250cc\n \nBumbu Dendeng : \n- Cabe merah 100gr \n-Bawang merah \n- Tomat 1 buah \n- Garam secukupnya\n \nCara membuat : \n1. Lumuri irisan daging sapi dengan garam, ungkep sampai daging kering dan bumbu meresap. \n2. Goreng daging sampai setengah matang. Angkat lalu memarkan. Goreng dendeng lagi sampai matang. \n3. Tumis bumbu yang telah dihaluskan menggunakan minyak sisa menggoreng dging sampai harum. Masukkan dendeng daging, aduk rata dan angkat. "},

            {  "Sate Padang","Durasi memasak : 30 menit","https://a4.pbase.com/g4/76/410576/2/64681107.TEDbka4v.jpg" ,
                    "Bahan Sate : \n- Daging sapi segar 1/2kg \n- Jeroan sapi 1/2kg \n- Serai 1 batang \n- Jahe 2cm, memarkan \n- Lengkuas 2cm, memarkan \n- Daun kunyit 1 lembar \n- Daun jeruk 4 lembar \n- Tepung beras 50gr (larutkan dengan sedikit air) \n- Air 1/2 liter\n \nBumbu Sate : \n- Cabe merah 4 buah \n- Bawang putih 5 siung \n- Bawang merah 6 butir \n- Ketumbar 2sdt \n- Jintang bubuk 1sdt \n- Merica bubuk 1/2sdt \n- Kunyit 5cm \n- Garam 1sdt \n- Gula pasir 1/2sdt\n \nPelengkap : \n- Lontong atau ketupat \n- Bawang goreng\n \nCara Membuat : \n1. Campurkan bumbu yang telah dihaluskan dengan daging dan jeroan sapi, diamkan 30 menit. Lalu masak dengan jahe, lengkuas, serai, daun jeruk dan daun kunyit sampai matang. Angkat dan sisihkan. \n2. Kentalkan kuah dengan larutan tepung beras sampai mengental. Siapkan tusukan sate. Tusuk daging yang telah dibumbui, panggang diatas api, angkat dan sajikan dengan ketupat atau lontong."},

            { "Ayam Pop", "Durasi memasak : 75 menit","https://resepmasakan309.files.wordpress.com/2016/03/ayam-pop.jpg?w=648",
                    "Bahan Ayam Pop : \n- Ayam kampung 1 ekor, potong 8 bagian \n- Cuka 1sdt \n- Air kelapa dari 1 butir kelapa\n \nBumbu Ayam Pop : \n- Bawang putih 5 siung \n- Merica 1/2sdt \n- Ketumbar 1/2 sdt\n \nCara Membuat : \n1. Rendam ayam dengan air dan tambahkan cuka selama 15 menit. Lumuri dengan bumbu yang telah dihaluskan. \n2. Masukkan ayam kedalam air kelapa ungkep diatas api kecil sampai matang dan air meresap. Setelah matang goreng ayam pop sebentar. Ayam pop siap dihidangkan."},

            {  "Sambal Lado Mudo", "Durasi memasak : 30 menit","https://obs.line-scdn.net/0hpUiej9ciL3pUHACfQQtQLW5KLBVncDx5MCp-ZARycU5xJWssYX9hT3gUcEh7f2gkOi9jFXcaNEt-fzwuP3hh/w644",
                    "Bahan Sambal Lado Mudo : \n- 30gr(2sdm) ikan teri nasi, goreng kering \n- 100gr cabe hijau kering \n- 100gr bawang merah, kupas \n- 2 siung bawang putih, kupas \n- 5 buah tomat hijau, potong 2 bagian \n- 10 lembar daun jeruk purut, sobek-sobek \nGaram 1/2sdt \n- Minyak sayur 100ml \n- Air untuk rebusan\n \nCara Membuat : \n1. Didihkan air, rebus cabe hijau, bawang merah, tomat hijau dan bawang putih sampai layu, angkat dan tiriskan. Sisihkan. \n2. Campurkan semua bahan yang sudah direbus beri sedikit garam, haluskan. Angkat. \n3. Panaskan minyak, masukkan cabe hijau yang telah dihaluskan, bersama ikan teri dan daun jeruk. Aduk sampai rata, masak sekitar 5 menit. Sambal siap disajikan."}
    };

    static ArrayList<Resep> getListData(){
        ArrayList<Resep> list = new ArrayList<>();
        for (String [] aData : RecipeDetail){
            Resep resep = new Resep ();
            resep.setName (aData[0]);
            resep.setDuration(aData[1]);
            resep.setPhoto(aData[2]);
            resep.setDetail(aData[3]);
            list.add(resep);
        }
        return list;
    }
}